blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/vue-telegram-mini-app?tab=readme-ov-file
    about: Check the documentation for guides and examples.
